# rust.yml
#
# github workflows action file for super-speedy-syslog-searcher
#
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
---
name: Rust
on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - .github/**
      - Cargo.toml
      - Cargo.lock
      - src/**.rs
  pull_request:
    paths:
      - .github/**
      - Cargo.toml
      - Cargo.lock
      - src/**.rs
      - benches/**
  workflow_dispatch:  # yamllint disable-line rule:empty-values
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  # MSRV
  # default rust version
  # should match first value in matrix.msrv
  MSRV_UPLOAD: 1.88.0
  # MSRV
  # rust version for llvm_cov job
  # should be equal or greater than $MSRV_UPLOAD
  VERSION_LLVM_COV: 1.88.0
  # version of flamegraph which is often using latest rust
  # so a specific version must be installed for the current MSRV
  FLAMEGRAPH_VERSION: "0.6.12"
  # run options for debug
  S4_ARGSD: --blocksz 0x2 -s
  # run options for release
  S4_ARGSR: --blocksz 0x40 -s
  # run files
  S4_TEST_FILES: \
    ./logs/CentOS9/x86_64/wtmp
    ./logs/other/tests/dtf2-2.log
    ./logs/other/tests/dtf3-2a.log
    ./logs/other/tests/dtf5-6a.log.gz
    ./logs/other/tests/dtf7-20-LEVELS.log.xz
    ./logs/other/tests/gen-2-1.tar
    ./logs/other/tests/gen-20-1-faces.log
    ./logs/other/tests/gen-20-1-⚀⚁⚂⚃⚄⚅.log
    ./logs/other/tests/gen-20-2-2-faces.log
    ./logs/programs/Event_Trace_Log/waasmedic.20251005_113019_195.etl
    ./logs/programs/evtx/Microsoft-Windows-Kernel-PnP__Configuration.evtx
    ./logs/programs/journal/RHE_91_system.journal
    ./logs/programs/journal/RHE_91_system.journal.gz
    ./logs/programs/OneDrive/Local/Microsoft/OneDrive/logs/Common/FileCoAuth-2025-12-21.1214.4056.1.odl
    ./logs/programs/strace/strace-unix,us_ls.out
    ./logs/programs/utmp/host-entry6.wtmp
    ./logs/programs/utmp/host-entry6.wtmp.bz2
    ./logs/programs/utmp/host-entry6.wtmp.gz
    ./logs/programs/utmp/host-entry6.wtmp.lz4
    ./logs/programs/utmp/host-entry6.wtmp.tar
    ./logs/programs/utmp/host-entry6.wtmp.xz
    ./logs/standards/ctime.log
    ./logs/standards/ISO8601-Date-Extend.log
    ./logs/standards/ISO8601-Date-Ordinal.log
    ./logs/standards/ISO8601-Date-Week.log
    ./logs/standards/ISO8601-YY-MM-DD.log
    ./logs/standards/ISO8601-YYYYDDMMTHHMM.log
    ./logs/standards/ISO8601-YYYYDDMMTHHMMSS.log
    ./logs/standards/ISO8601-YYYYMM.log
    ./logs/standards/ISO8601-YYYYMMDD.log
    ./logs/standards/ISO8601-YYYY-DD-MMTHH-MM-SS.log
    ./logs/standards/ISO8601-YYYY-DDD.log
    ./logs/standards/ISO8601-YYYY-MM-DD.log
    ./logs/standards/RFC-2822.log
    ./logs/standards/RFC-3164.log
    ./logs/standards/RFC-5424-2dot-0400.log
    ./logs/standards/RFC-5424-2dotZ.log
    ./logs/standards/RFC-5424-3dotZ.log
    ./logs/standards/RFC-5424-6dot-0700.log
    ./logs/standards/Unix-ms.log
    ./logs/standards/W3C-DTF.log

jobs:

  job_rust_msrv_os:
    # this job downloads and builds dependency crates
    name: build ${{ matrix.msrv }} on ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # MSRV
        # first `msrv` should match Cargo.toml:[package]:rust-version
        # add a few more for sanity checks (you might be surprised)
        # concise listing at https://releases.rs/
        msrv: [
          "1.88.0",  # MSRV
          "1.90.0",
          "1.94.1",
        ]
        exclude:
          # for mac and windows, only run MSRV
          - os: macos-latest
            msrv: "1.90.0"
          - os: macos-latest
            msrv: "1.94.1"
          - os: windows-latest
            msrv: "1.90.0"
          - os: windows-latest
            msrv: "1.94.1"
    runs-on: ${{ matrix.os }}
    steps:
      # Issue #62: `git config` to workaround `git checkout` error on Windows
      - run: |
          git config --global core.protectNTFS false
      - uses: actions/checkout@v6
      # TODO: use `https://github.com/actions-rust-lang/setup-rust-toolchain`?
      #       why did I stop using it?
      - run: rustup toolchain install ${{ matrix.msrv }} --profile minimal
      - name: print default-target
        shell: bash
        run: |
          set -eux
          cargo install --locked default-target
          ~/.cargo/bin/default-target
      - name: Build rust ${{ matrix.msrv }} on ${{ matrix.os }} --profile release
        shell: bash
        run: |
          set -eux
          export CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true
          export S4_BUILD_REGEX=1
          export S4_BUILD_REGEX_PRINT=1
          cargo --version
          rustc --print cfg
          cargo build --locked --profile release
          ./target/release/s4 --version
      - name: Build rust ${{ matrix.msrv }} on ${{ matrix.os }} --profile dev
        shell: bash
        run: |
          set -eux
          export CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true
          export S4_BUILD_REGEX=1
          export S4_BUILD_REGEX_PRINT=1
          cargo build --locked --profile dev
          ./target/debug/s4 --version
      - name: Build rust ${{ matrix.msrv }} on ${{ matrix.os }} --profile mimalloc
        shell: bash
        run: |
          set -eux
          export CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true
          export S4_BUILD_REGEX=1
          export S4_BUILD_REGEX_PRINT=1
          cargo build --locked --profile mimalloc --features mimalloc
          ./target/mimalloc/s4 --version
      - name: Build rust ${{ matrix.msrv }} on ${{ matrix.os }} --profile rpmalloc
        shell: bash
        run: |
          set -eux
          export CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true
          export S4_BUILD_REGEX=1
          export S4_BUILD_REGEX_PRINT=1
          cargo build --locked --profile rpmalloc --features rpmalloc
          ./target/rpmalloc/s4 --version
      - name: Build rust ${{ matrix.msrv }} on ${{ matrix.os }} --profile jemalloc
        shell: bash
        # jemalloc builds fails on github Windows
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          set -eux
          export CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true
          export S4_BUILD_REGEX=1
          export S4_BUILD_REGEX_PRINT=1
          cargo build --locked --profile jemalloc --features jemalloc
          ./target/jemalloc/s4 --version
      # skip tcmalloc as it requires too particular installed libraries
      - name: Build rust ${{ matrix.msrv }} on ${{ matrix.os }} --profile alloc_tracker
        shell: bash
        run: |
          set -eux
          export S4_BUILD_REGEX=79
          export S4_BUILD_REGEX_PRINT=1
          export RUST_MIN_STACK=15000000  # 15 MB
          cargo build --locked --profile alloc_tracker --features alloc_tracker
          export S4_ALLOC_TRACKER_PRINT=1
          ./target/alloc_tracker/s4 --version
          ./target/alloc_tracker/s4 ./logs/other/tests/dtf2-2.log
      - name: Build rust ${{ matrix.msrv }} on ${{ matrix.os }} --profile flamegraph
        shell: bash
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          set -eux
          export S4_BUILD_REGEX=1
          export S4_BUILD_REGEX_PRINT=1
          RUSTFLAGS=-g cargo build --profile flamegraph
          ./target/flamegraph/s4 --version

  job_build_debug_release:
    # this job downloads and builds dependency crates
    name: build debug and release, upload
    needs: [job_rust_msrv_os]
    runs-on: ubuntu-latest
    steps:
      # build & upload debug
      - name: git checkout
        uses: actions/checkout@v6
      - run: rustup toolchain install ${{ env.MSRV_UPLOAD }} --profile minimal
      - name: Build Debug
        shell: bash
        run: |
          set -eux
          cargo --version
          export S4_BUILD_REGEX_PRINT=1
          cargo build --locked --verbose
          cp -av ./target/debug/s4 ./s4_debug
          ./s4_debug --version
      - name: Upload debug binary for test
        uses: actions/upload-artifact@v6
        with:
          name: s4_debug
          path: ./s4_debug
      # build & upload release
      - name: Build Release
        shell: bash
        run: |
          set -eux
          cargo --version
          export S4_BUILD_REGEX_PRINT=1
          cargo build --locked --release
          cp -av ./target/release/s4 ./s4_release
          ./s4_release --version
      - name: Upload release binary for test
        uses: actions/upload-artifact@v6
        with:
          name: s4_release
          path: ./s4_release
      - name: Upload release binary (Ubuntu Linux)
        uses: actions/upload-artifact@v6
        with:
          name: s4
          path: ./target/release/s4

  job_cross_targets:
    name: cross ${{ matrix.target }} on ubuntu-latest
    needs: [job_rust_msrv_os]
    strategy:
      matrix:
        target:
          # pre-test these using ./tools/cross-checks.sh
          # Tier 1
          - aarch64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
          - x86_64-unknown-linux-gnu
          # Tier 2
          - aarch64-unknown-linux-musl
          - arm-linux-androideabi
          - arm-unknown-linux-gnueabi
          - arm-unknown-linux-gnueabihf
          - armv7-linux-androideabi
          - armv7-unknown-linux-gnueabihf
          - armv7-unknown-linux-musleabihf
          - riscv64gc-unknown-linux-gnu
          - s390x-unknown-linux-gnu
          - thumbv7neon-linux-androideabi
          - x86_64-unknown-freebsd
          - x86_64-unknown-illumos
          - x86_64-unknown-linux-musl
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v6
      - run: rustup toolchain install ${{ env.MSRV_UPLOAD }} --target ${{ matrix.target }} --profile minimal
      - run: rustup target add ${{ matrix.target }}
      - run: cargo install --locked cross
      - name: cross check ${{ matrix.target }}
        shell: bash
        run: |
          set -eux
          uname -a
          rustup show
          cross --version
          # force S4_BUILD_REGEX=1 because env. vars. are not passed by `cross` into
          # the docker instance.
          echo 1 | tee ./subprojects/ere/ere_datetimes_impl/S4_BUILD_REGEX S4_BUILD_REGEX
          export S4_BUILD_REGEX_PRINT=1
          cross check --locked --lib --bins --release --target ${{ matrix.target }}

  job_cross_targets_macos:
    name: cross ${{ matrix.target }} on macos-13
    needs: [job_rust_msrv_os, job_cross_targets]
    strategy:
      matrix:
        target:
          # Tier 1
          - x86_64-apple-darwin
          # Tier 2 with host tools
          - aarch64-apple-darwin
    runs-on: macos-13
    steps:
      - name: git checkout
        uses: actions/checkout@v6
      - run: rustup toolchain install ${{ env.MSRV_UPLOAD }} --target ${{ matrix.target }} --profile minimal
      - run: rustup target add ${{ matrix.target }}
      - run: cargo install --locked cross
      - name: cross check ${{ matrix.target }}
        shell: bash
        run: |
          set -eux
          uname -a
          rustup show
          cross --version
          echo 1 > S4_BUILD_REGEX
          export S4_BUILD_REGEX=1
          export S4_BUILD_REGEX_PRINT=1
          cross check --locked --lib --bins --release --target ${{ matrix.target }}

  job_cross_targets_windows:
    name: cross ${{ matrix.target }} on windows
    needs: [job_rust_msrv_os, job_cross_targets_macos]
    strategy:
      matrix:
        target:
          # Tier 1
          - i686-pc-windows-msvc
          - x86_64-pc-windows-msvc
    runs-on: windows-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v6
      - run: rustup toolchain install ${{ env.MSRV_UPLOAD }} --target ${{ matrix.target }} --profile minimal
      - run: rustup target add ${{ matrix.target }}
      - run: cargo install --locked cross
      - name: cross check ${{ matrix.target }}
        shell: powershell
        run: |
          Set-PSDebug -Trace 1
          rustup.exe show
          cross.exe --version
          Write-Output 1 > S4_BUILD_REGEX
          Write-Output 1 > ./subprojects/ere/ere_datetimes_impl/S4_BUILD_REGEX
          ${env:S4_BUILD_REGEX}="1"
          ${env:S4_BUILD_REGEX_PRINT}="1"
          cross.exe check --locked --lib --bins --release --target ${{ matrix.target }}

  # job_test_wasm:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v6
  #    - uses: moonrepo/setup-rust@v1
  #      with:
  #        channel: ${{ env.MSRV_UPLOAD }}
  #        bins: cargo-wasi
  #        targets: wasm32-wasi
  #    - uses: mwilliamson/setup-wasmtime-action@v2
  #      with:
  #        wasmtime-version: "12.0.1"
  #    # can not compile `filepath`
  #    # see https://github.com/evilpie/filepath/issues/6
  #    - run: cargo wasi test --color=always -- --color=always

  job_check:
    # this job downloads and builds dependency crates
    name: check
    needs: [job_rust_msrv_os]
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v6
      - run: rustup toolchain install ${{ env.MSRV_UPLOAD }} --profile minimal
      - name: Check
        shell: bash
        # `cargo check` builds dependences and other things but skips
        # final code generation
        run: |
          set -eux
          cargo --version
          export S4_BUILD_REGEX=1
          export S4_BUILD_REGEX_PRINT=1
          cargo check --locked --all-targets
          cargo check --locked --all-targets --release

  job_deny:
    name: cargo deny
    needs: [job_rust_msrv_os]
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v6
      - run: rustup toolchain install ${{ env.MSRV_UPLOAD }} --profile minimal
      - run: cargo install --locked cargo-deny
      - name: Run cargo-deny.sh
        shell: bash
        run: ./tools/cargo-deny.sh
        continue-on-error: true

  job_clippy:
    # this job downloads and builds dependency crates
    name: clippy
    needs: [job_rust_msrv_os]
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v6
      - run: rustup toolchain install ${{ env.MSRV_UPLOAD }} --profile default
      - name: Clippy
        shell: bash
        run: |
          set -eux
          cargo --version
          cargo clippy --version
          cargo clippy --locked --no-deps --all-targets --all-features

  job_bench:
    # this job downloads and builds dependency crates
    name: bench
    needs: [job_rust_msrv_os]
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v6
      - run: rustup toolchain install ${{ env.MSRV_UPLOAD }} --profile minimal
      - name: Bench Dry Run
        shell: bash
        run: |
          set -eux
          cargo --version
          export S4_BUILD_REGEX=1
          export S4_BUILD_REGEX_PRINT=1
          cargo bench --locked --no-run --features bench_jetscii,bench_memchr,bench_stringzilla

  job_test_linux:
    # this job downloads and builds dependency crates
    name: test Linux
    needs: [job_rust_msrv_os]
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v6
      - run: rustup toolchain install ${{ env.MSRV_UPLOAD }} --profile minimal
      - run: cargo install --locked cargo-nextest
      - name: Install libsystemd
        shell: bash
        run: |
          set -eux
          uname -a
          sudo apt update || true
          (find / -xdev \
                  \( -type f -o -type l \) \
                  -name 'libsystemd*' 2>/dev/null || true) \
              | sort
          sudo apt install --yes libsystemd0
          (find / -xdev \
                  \( -type f -o -type l \) \
                  -name 'libsystemd*' 2>/dev/null || true) \
              | sort
      - name: set log file filesystem Modified Times
        shell: bash
        run: |
          set -eux
          bash --version
          grep --version
          chmod -v +x ./tools/log-files-time-update.sh
          ./tools/log-files-time-update.sh
      - name: test (limited)
        # sanity check tests requiring libsystemd can run
        shell: bash
        run: |
          set -eux
          # can libsystemd be found?
          (find / -xdev \
                  \( -type f -o -type l \) \
                  -name 'libsystemd*' 2>/dev/null || true) \
              | sort
          # run tests that use libsystemd
          cargo test --locked tests::journalreader_tests
      - name: create venv
        shell: bash
        run: |
          set -eux
          S4_BUILD_REGEX=1
          S4_BUILD_REGEX_PRINT=1
          cargo build --locked --profile release_Opt0
          which python
          python --version
          ./target/release_Opt0/s4 --venv
      - name: nextest (all)
        shell: bash
        run: |
          set -eux
          bash --version
          cargo nextest --version
          export NEXTEST_TEST_THREADS=1
          cargo nextest run --locked --bins --lib --no-fail-fast --final-status-level=fail

  job_test_macos:
    name: test Mac
    needs: [job_rust_msrv_os]
    runs-on: macos-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v6
      - run: rustup toolchain install ${{ env.MSRV_UPLOAD }} --profile minimal
      - run: cargo install --locked cargo-nextest
      # XXX: MacOS tools do not support `touch` arguments run in
      #      `./tools/log-files-time-update.sh`. So skip running `log-files-time-update.sh`
      #      See https://stackoverflow.com/q/78540977/471376
      - name: create venv
        shell: bash
        run: |
          set -eux
          export S4_BUILD_REGEX=1
          export S4_BUILD_REGEX_PRINT=1
          cargo build --locked --profile release_Opt0
          which python
          python --version
          ./target/release_Opt0/s4 --venv
      - name: nextest (all)
        shell: bash
        run: |
          set -eux
          cargo nextest --version
          export NEXTEST_TEST_THREADS=1
          cargo nextest run --locked --bins --lib --no-fail-fast --final-status-level=fail

  job_test_windows:
    name: test Windows
    needs: [job_rust_msrv_os]
    runs-on: windows-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v6
      - run: rustup toolchain install ${{ env.MSRV_UPLOAD }} --profile minimal
      - name: set log file filesystem Modified Times
        shell: powershell
        run: |
          .\tools\log-files-time-update.ps1
      - name: create venv
        shell: powershell
        run: |
          Set-PSDebug -Trace 1
          ${env:S4_BUILD_REGEX}="1"
          ${env:S4_BUILD_REGEX_PRINT}="1"
          cargo.exe build --locked --profile release_Opt0
          Get-Command -All python.exe
          python.exe --version
          ./target/release_Opt0/s4 --venv
      - name: test (all)
        shell: powershell
        run: |
          Set-PSDebug -Trace 1
          # XXX: do not use nextest as it is buggy on Windows
          #      see Issue #218
          cargo.exe test --locked --bins --lib --no-fail-fast

  job_doc_publish:
    # this job downloads and builds dependency crates
    name: doc, publish
    needs: [job_rust_msrv_os]
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v6
      - name: Build Documentation
        run: cargo doc --locked --release --no-deps -v
      - name: Publish Dry Run
        shell: bash
        run: |
          set -eux
          cargo publish --locked --dry-run
          cargo package --list --all-features
          cargo package --locked

  job_yamllint:
    # this job installs Python PIP packages
    name: yamllint
    needs: [job_rust_msrv_os]
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v6
      - name: Use Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          set -eux
          python --version
          python -m pip \
            --disable-pip-version-check \
            --no-python-version-warning \
            --version
          python -m pip install \
            --disable-pip-version-check \
            --no-python-version-warning \
            --no-color \
            yamllint==1.35.1
          python -m pip list \
            --disable-pip-version-check \
            --no-python-version-warning \
            -v -v
      - name: Run yamllint.sh
        run: PYTHON=python ./tools/yamllint.sh --format github

  job_codecov_validate:
    name: codecov validate
    needs: [job_rust_msrv_os]
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v6
      - name: Run codecov-validate.sh
        run: ./tools/codecov-validate.sh -v

  job_markup_link_checker:
    name: markup link checker
    needs: [job_rust_msrv_os]
    runs-on: ubuntu-latest
    steps:
      - name: Markup Link Checker (mlc)
        uses: becheran/mlc@v0.17.1
        with:
          args: ./README.md

  job_runs:
    # all of these steps need the s4 binary and the git-committed logs
    # with modified filesystem datetime
    name: run s4
    needs: job_build_debug_release
    runs-on: ubuntu-latest
    steps:
      # checkout for the log files
      - name: git checkout
        uses: actions/checkout@v6
      - run: rustup toolchain install ${{ env.MSRV_UPLOAD }} --profile minimal
      - name: set log file filesystem Modified Times
        shell: bash
        run: |
          set -eux
          bash --version
          grep --version
          chmod -v +x ./tools/log-files-time-update.sh
          ./tools/log-files-time-update.sh
      - name: Install libsystemd
        shell: bash
        run: |
          set -eux
          sudo apt update || true
          sudo apt install --yes libsystemd0
      # download debug
      - name: Download debug binary
        uses: actions/download-artifact@v4
        with:
          name: s4_debug
      # download release
      - name: Download release binary
        uses: actions/download-artifact@v4
        with:
          name: s4_release
      # run debug
      - name: s4_debug --help
        shell: bash
        run: |
          set -eux
          (find / -xdev \
                  \( -type f -o -type l \) \
                  -name 'libsystemd*' 2>/dev/null || true) \
              | sort
          S4=./s4_debug
          chmod -v +x -- ${S4}
          ${S4} --version
          ${S4} --help
      - name: s4_debug --venv
        shell: bash
        run: |
          set -eux
          sudo apt install python3
          which python3
          python3 --version
          S4=./s4_debug
          chmod -v +x -- ${S4}
          ${S4} --venv
      - name: s4_debug --color=never S4_TEST_FILES
        shell: bash
        run: |
          set -eux
          S4=./s4_debug
          chmod -v +x -- ${S4}
          ${S4} --color=never ${S4_TEST_FILES} 2>/dev/null
      - name: s4_debug S4_ARGSD --color=never S4_TEST_FILES
        shell: bash
        run: |
          set -eux
          S4=./s4_debug
          chmod -v +x -- ${S4}
          ${S4} ${S4_ARGSD} --color=never ${S4_TEST_FILES} 2>/dev/null
      - name: s4_debug S4_ARGSD --color=never -l -n -w S4_TEST_FILES
        shell: bash
        run: |
          set -eux
          S4=./s4_debug
          chmod -v +x -- ${S4}
          ${S4} ${S4_ARGSD} --color=never -l -n -w ${S4_TEST_FILES} 2>/dev/null
      - name: s4_debug S4_ARGSD --color=never -l -p -w S4_TEST_FILES
        shell: bash
        run: |
          set -eux
          S4=./s4_debug
          chmod -v +x -- ${S4}
          ${S4} ${S4_ARGSD} --color=never -l -p -w ${S4_TEST_FILES} 2>/dev/null
      - name: s4_debug S4_ARGSD --color=never -u -n -w S4_TEST_FILES
        shell: bash
        run: |
          set -eux
          S4=./s4_debug
          chmod -v +x -- ${S4}
          ${S4} ${S4_ARGSD} --color=never -u -n -w ${S4_TEST_FILES} 2>/dev/null
      - name: s4_debug S4_ARGSD --color=never -u -p -w S4_TEST_FILES
        shell: bash
        run: |
          set -eux
          S4=./s4_debug
          chmod -v +x -- ${S4}
          ${S4} ${S4_ARGSD} --color=never -u -p -w ${S4_TEST_FILES} 2>/dev/null
      - name: s4_debug S4_ARGSD --color=never -l -n -w S4_TEST_FILES
        shell: bash
        run: |
          set -eux
          S4=./s4_debug
          chmod -v +x -- ${S4}
          ${S4} ${S4_ARGSD} --color=always -l -n -w ${S4_TEST_FILES} 2>/dev/null
      - name: s4_debug S4_ARGSD --color=never -l -p -w S4_TEST_FILES
        shell: bash
        run: |
          set -eux
          S4=./s4_debug
          chmod -v +x -- ${S4}
          ${S4} ${S4_ARGSD} --color=always -l -p -w ${S4_TEST_FILES} 2>/dev/null
      - name: s4_debug S4_ARGSD --color=never -u -n -w S4_TEST_FILES
        shell: bash
        run: |
          set -eux
          S4=./s4_debug
          chmod -v +x -- ${S4}
          ${S4} ${S4_ARGSD} --color=always -u -n -w ${S4_TEST_FILES} 2>/dev/null
      - name: s4_debug S4_ARGSD --color=never -u -p -w S4_TEST_FILES
        shell: bash
        run: |
          set -eux
          S4=./s4_debug
          chmod -v +x -- ${S4}
          ${S4} ${S4_ARGSD} --color=always -u -p -w ${S4_TEST_FILES} 2>/dev/null
      - name: s4_debug -s S4_ARGSD --color=never -l -n -w S4_TEST_FILES
        shell: bash
        run: |
          set -eux
          S4=./s4_debug
          chmod -v +x -- ${S4}
          ${S4} -s --color=never -l -n -w ${S4_TEST_FILES} &>/dev/null
      - name: s4_debug -s S4_ARGSD --color=never -l -p -w S4_TEST_FILES
        shell: bash
        run: |
          set -eux
          S4=./s4_debug
          chmod -v +x -- ${S4}
          ${S4} -s --color=never -l -p -w ${S4_TEST_FILES} &>/dev/null
      - name: s4_debug -s S4_ARGSD --color=never -u -n -w S4_TEST_FILES
        shell: bash
        run: |
          set -eux
          S4=./s4_debug
          chmod -v +x -- ${S4}
          ${S4} -s --color=never -u -n -w ${S4_TEST_FILES} &>/dev/null
      - name: s4_debug -s S4_ARGSD --color=never -u -p -w S4_TEST_FILES
        shell: bash
        run: |
          set -eux
          S4=./s4_debug
          chmod -v +x -- ${S4}
          ${S4} -s --color=never -u -p -w ${S4_TEST_FILES} &>/dev/null
      - name: s4_debug -s S4_ARGSD --color=always -l -n -w S4_TEST_FILES
        shell: bash
        run: |
          set -eux
          S4=./s4_debug
          chmod -v +x -- ${S4}
          ${S4} -s --color=always -l -n -w ${S4_TEST_FILES} &>/dev/null
      - name: s4_debug -s S4_ARGSD --color=always -l -p -w S4_TEST_FILES
        shell: bash
        run: |
          set -eux
          S4=./s4_debug
          chmod -v +x -- ${S4}
          ${S4} -s --color=always -l -p -w ${S4_TEST_FILES} &>/dev/null
      - name: s4_debug -s S4_ARGSD --color=always -u -n -w S4_TEST_FILES
        shell: bash
        run: |
          set -eux
          S4=./s4_debug
          chmod -v +x -- ${S4}
          ${S4} -s --color=always -u -n -w ${S4_TEST_FILES} &>/dev/null
      - name: s4_debug -s S4_ARGSD --color=always -u -p -w S4_TEST_FILES
        shell: bash
        run: |
          set -eux
          S4=./s4_debug
          chmod -v +x -- ${S4}
          ${S4} -s --color=always -u -p -w ${S4_TEST_FILES} &>/dev/null
      - name: s4_debug -s S4_ARGSD --color=always --light-theme -u -p -w S4_TEST_FILES
        shell: bash
        run: |
          set -eux
          S4=./s4_debug
          chmod -v +x -- ${S4}
          ${S4} -s --color=always --light-theme -u -p -w ${S4_TEST_FILES} &>/dev/null
      # run release
      - name: s4_release --help
        shell: bash
        run: |
          set -eux
          S4=./s4_release
          chmod -v +x -- ${S4}
          ${S4} --version
          ${S4} --help
      - name: s4_release --venv
        shell: bash
        run: |
          set -eux
          which python3
          python3 --version
          S4=./s4_release
          ${S4} --venv
      - name: s4_release --color=never S4_TEST_FILES
        shell: bash
        run: |
          set -eux
          S4=./s4_release
          chmod -v +x -- ${S4}
          ${S4} --color=never ${S4_TEST_FILES}
      - name: s4_release S4_ARGSR --color=never S4_TEST_FILES
        shell: bash
        run: |
          set -eux
          S4=./s4_release
          chmod -v +x -- ${S4}
          ${S4} ${S4_ARGSR} --color=never ${S4_TEST_FILES}
      - name: s4_release S4_ARGSR --color=never -l -n -w S4_TEST_FILES
        shell: bash
        run: |
          set -eux
          S4=./s4_release
          chmod -v +x -- ${S4}
          ${S4} ${S4_ARGSR} --color=never -l -n -w ${S4_TEST_FILES}
      - name: s4_release S4_ARGSR --color=never -l -p -w S4_TEST_FILES
        shell: bash
        run: |
          set -eux
          S4=./s4_release
          chmod -v +x -- ${S4}
          ${S4} ${S4_ARGSR} --color=never -l -p -w ${S4_TEST_FILES}
      - name: s4_release S4_ARGSR --color=never -u -n -w S4_TEST_FILES
        shell: bash
        run: |
          set -eux
          S4=./s4_release
          chmod -v +x -- ${S4}
          ${S4} ${S4_ARGSR} --color=never -u -n -w ${S4_TEST_FILES}
      - name: s4_release S4_ARGSR --color=never -u -p -w S4_TEST_FILES
        shell: bash
        run: |
          set -eux
          S4=./s4_release
          chmod -v +x -- ${S4}
          ${S4} ${S4_ARGSR} --color=never -u -p -w ${S4_TEST_FILES}
      - name: s4_release S4_ARGSR --color=never -l -n -w S4_TEST_FILES
        shell: bash
        run: |
          set -eux
          S4=./s4_release
          chmod -v +x -- ${S4}
          ${S4} ${S4_ARGSR} --color=always -l -n -w ${S4_TEST_FILES}
      - name: s4_release S4_ARGSR --color=never -l -p -w S4_TEST_FILES
        shell: bash
        run: |
          set -eux
          S4=./s4_release
          chmod -v +x -- ${S4}
          ${S4} ${S4_ARGSR} --color=always -l -p -w ${S4_TEST_FILES}
      - name: s4_release S4_ARGSR --color=always -u -n -w S4_TEST_FILES
        shell: bash
        run: |
          set -eux
          S4=./s4_release
          chmod -v +x -- ${S4}
          ${S4} ${S4_ARGSR} --color=always -u -n -w ${S4_TEST_FILES}
      - name: s4_release S4_ARGSR --color=always -u -p -w S4_TEST_FILES
        shell: bash
        run: |
          set -eux
          S4=./s4_release
          chmod -v +x -- ${S4}
          ${S4} ${S4_ARGSR} --color=always -u -p -w ${S4_TEST_FILES}
      - name: s4_release -s --color=always S4_TEST_FILES
        shell: bash
        run: |
          set -eux
          S4=./s4_release
          chmod -v +x -- ${S4}
          ${S4} -s --color=never ${S4_TEST_FILES} &>/dev/null
      - name: s4_release -s --color=never -l -n -w S4_TEST_FILES
        shell: bash
        run: |
          set -eux
          S4=./s4_release
          chmod -v +x -- ${S4}
          ${S4} -s --color=never -l -n -w ${S4_TEST_FILES} &>/dev/null
      - name: s4_release -s --color=never -l -p -w S4_TEST_FILES
        shell: bash
        run: |
          set -eux
          S4=./s4_release
          chmod -v +x -- ${S4}
          ${S4} -s --color=never -l -p -w ${S4_TEST_FILES} &>/dev/null
      - name: s4_release -s --color=never -u -n -w S4_TEST_FILES
        shell: bash
        run: |
          set -eux
          S4=./s4_release
          chmod -v +x -- ${S4}
          ${S4} -s --color=never -u -n -w ${S4_TEST_FILES} &>/dev/null
      - name: s4_release -s --color=never -u -p -w S4_TEST_FILES
        shell: bash
        run: |
          set -eux
          S4=./s4_release
          chmod -v +x -- ${S4}
          ${S4} -s --color=never -u -p -w ${S4_TEST_FILES} &>/dev/null
      - name: s4_release -s --color=always -l -n -w S4_TEST_FILES
        shell: bash
        run: |
          set -eux
          S4=./s4_release
          chmod -v +x -- ${S4}
          ${S4} -s --color=always -l -n -w ${S4_TEST_FILES} &>/dev/null
      - name: s4_release -s --color=always -l -p -w S4_TEST_FILES
        shell: bash
        run: |
          set -eux
          S4=./s4_release
          chmod -v +x -- ${S4}
          ${S4} -s --color=always -l -p -w ${S4_TEST_FILES} &>/dev/null
      - name: s4_release -s --color=always -u -n -w S4_TEST_FILES
        shell: bash
        run: |
          set -eux
          S4=./s4_release
          chmod -v +x -- ${S4}
          ${S4} -s --color=always -u -n -w ${S4_TEST_FILES} &>/dev/null
      - name: s4_release -s --color=always -u -p -w S4_TEST_FILES
        shell: bash
        run: |
          set -eux
          S4=./s4_release
          chmod -v +x -- ${S4}
          ${S4} -s --color=always -u -p -w ${S4_TEST_FILES} &>/dev/null
      - name: s4_release -s --color=always --light-theme -u -p -w S4_TEST_FILES
        shell: bash
        run: |
          set -eux
          S4=./s4_release
          chmod -v +x -- ${S4}
          ${S4} -s --color=always --light-theme -u -p -w ${S4_TEST_FILES} &>/dev/null
      # compare debug release
      - name: Run Script compare-debug-release.sh
        shell: bash
        run: |
          set -eux
          export PROGRAM_A=./s4_release
          export PROGRAM_B=./s4_debug
          SCRIPT=./tools/compare-debug-release.sh
          chmod -v +x -- "${PROGRAM_A}" "${PROGRAM_B}" "${SCRIPT}" ./tools/compare-two-s4.sh
          "${SCRIPT}"
      # compare grep sort
      - name: Run Script compare-grep-sort.sh
        shell: bash
        run: |
          set -eux
          export PROGRAM=./s4_release
          SCRIPT=./tools/compare-grep-sort.sh
          chmod -v +x -- "${PROGRAM}" "${SCRIPT}"
          "${PROGRAM}" --version
          "${SCRIPT}"
      # compare current and expected
      - name: Run Script compare-current-and-expected
        shell: bash
        run: |
          set -eux
          export PROGRAM=./s4_release
          SCRIPT=./tools/compare-current-and-expected/compare.sh
          chmod -v +x -- "${PROGRAM}" "${SCRIPT}"
          "${PROGRAM}" --version
          "${SCRIPT}"
      # compare cat
      - name: Run Script compare-cat
        shell: bash
        run: |
          set -eux
          export PROGRAM=./s4_release
          SCRIPT=./tools/compare-cat.sh
          chmod -v +x -- "${PROGRAM}" "${SCRIPT}"
          "${PROGRAM}" --version
          "${SCRIPT}"

  # Run code coverage using cargo-llvm-cov then upload to coveralls.io
  job_code_coverage_llvm:
    name: llvm-cov
    runs-on: ubuntu-latest
    needs: job_runs
    env:
      COVERALLS_FILE: ./coveralls.lcov
    steps:
      - name: git checkout
        uses: actions/checkout@v6
      - run: rustup toolchain install ${{ env.VERSION_LLVM_COV }} --profile minimal
      - run: rustup component add llvm-tools-preview
      - run: cargo install --locked cargo-llvm-cov
      - name: Install libsystemd
        shell: bash
        run: |
          set -eux
          sudo apt update || true
          sudo apt install --yes libsystemd0 lcov
      - name: set log file filesystem Modified Times
        shell: bash
        run: |
          set -eux
          bash --version
          grep --version
          chmod -v +x ./tools/log-files-time-update.sh
          ./tools/log-files-time-update.sh
      - name: run llvm-cov
        shell: bash
        run: |
          set -eux
          chmod -v +x ./tools/cargo-llvm-cov-combine-multiple.sh
          cargo llvm-cov --version
          cargo llvm-cov show-env
          LCOV_OUTPUT_SUMMARY=${COVERALLS_FILE} ./tools/cargo-llvm-cov-combine-multiple.sh
          ls -l "${COVERALLS_FILE}"
      - name: upload coveralls
        uses: coverallsapp/github-action@v2
        with:
          file: ${{ env.COVERALLS_FILE }}
          format: lcov
...
